# Default values for snmp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.local:9001/local/snmp
  tag: 1.0.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

configmap:
  name_snmpd: snmpd-etc-config

deployment:
  master_agent_host: localhost

service:
  name: snmpd-service
  type: NodePort

