# Default values for snmp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

snmp:
  image:
    repository: docker.io/starlingx/stx-snmp
    tag: stx.8.0-v1.0.0
  pull_policy: IfNotPresent

subagent:
  name: sub-agent
  image:
    repository: docker.io/starlingx/stx-fm-subagent
    tag: stx.8.0-v1.0.0
  pull_policy: IfNotPresent

trap_subagent:
  name: trap-subagent
  image:
    repository: docker.io/starlingx/stx-fm-trap-subagent
    tag: stx.8.0-v1.0.0
  pull_policy: IfNotPresent

image:
  debug: ''

nameOverride: ""
fullnameOverride: ""

nodeSelector: { node-role.kubernetes.io/control-plane: "" }

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"

configmap:
  name_snmpd: snmpd-etc-config
  name_fm: snmpd-fm
  user_conf: '# User configuration'
  system_description: ''
  system_contact: ''
  system_name: ''
  system_location: ''
  connection: ''

deployment:
  master_agent_host: localhost
  master_agent_port: 705
  master_agent_connection_retries: 20

service:
  name: snmpd-service
  type: NodePort

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 1

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 1
