# Default values for snmp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/starlingx/stx-snmp
  tag: stx.5.0-v1.0.0
  pullPolicy: IfNotPresent
  subagent_name: sub-agent
  repository_subagent: docker.io/starlingx/stx-fm-subagent
  tag_subagent: stx.5.0-v1.0.2
  pullPolicy_subagent: IfNotPresent
  trap_subagent_name: trap-subagent
  repository_trap_subagent: docker.io/starlingx/stx-fm-trap-subagent
  tag_trap_subagent: stx.5.0-v1.0.2
  pullPolicy_trap_subagent: IfNotPresent
  debug: ''

nameOverride: ""
fullnameOverride: ""

configmap:
  name_snmpd: snmpd-etc-config
  name_fm: snmpd-fm
  user_conf: '# User configuration'
  system_description: ''
  system_contact: ''
  system_name: ''
  system_location: ''
  connection: ''

deployment:
  master_agent_host: localhost
  master_agent_port: 705
  master_agent_connection_retries: 20

service:
  name: snmpd-service
  type: NodePort

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 1

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 1
