---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: snmp
data:
  chart_name: snmp
  release: snmp
  namespace: kube-system
  source:
    location: http://172.17.0.1:8080/helm_charts/stx-platform/snmp-1.0.0.tgz
    subpath: snmp
    type: tar
    reference: master
  wait:
    timeout: 1800
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            app: snmp
  dependencies: []
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: snmp
data:
  description: "StarlingX SNMP"
  sequenced: false
  chart_group:
    - snmp
---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: snmp-manifest
data:
  release_prefix: ns
  chart_groups:
    - snmp
