apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name_snmpd }}
data:
{{ (.Files.Glob "snmpd/*").AsConfig | indent 2 }}
{{ .Values.configmap.user_conf | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name_fm }}
data:
  fm.conf: |
    sql_connection={{ .Values.configmap.connection }}

