apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snmp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "snmp.name" . }}
    helm.sh/chart: {{ include "snmp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "snmp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "snmp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 161
            protocol: UDP
          - containerPort: 162
            protocol: UDP
          volumeMounts:
          - name: snmpd-etc-volume
            mountPath: /etc/snmp
      volumes:
      - name: snmpd-etc-volume
        configMap:
          name: {{ .Values.configmap.name_snmpd }}
