apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snmp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "snmp.name" . }}
    helm.sh/chart: {{ include "snmp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "snmp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "snmp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      imagePullSecrets:
        - name: default-registry-key
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 161
            protocol: UDP
          - containerPort: 162
            protocol: UDP
          - containerPort: 705
            protocol: TCP
          # Issues with liveness and readiness: https://bit.ly/3nVRQrL
          # K8s issue related: https://github.com/kubernetes/kubernetes/issues/81713
          #
          # livenessProbe:
          #   tcpSocket:
          #     port: 705
          #   initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          #   timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          #   successThreshold: {{ .Values.livenessProbe.successThreshold }}
          #   failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          # readinessProbe:
          #   tcpSocket:
          #     port: 705
          #   initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          #   timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          #   successThreshold: {{ .Values.readinessProbe.successThreshold }}
          #   failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          volumeMounts:
          - name: snmpd-etc-volume
            mountPath: /etc/snmp
        - name: {{ .Values.image.subagent_name }}
          image: "{{ .Values.image.repository_subagent }}:{{ .Values.image.tag_subagent }}"
          imagePullPolicy: {{ .Values.image.pullPolicy_subagent }}
          volumeMounts:
          - name: snmpd-fm-volume
            mountPath: /etc/fm/
          # Fail on liveness and readiness as here: https://bit.ly/3nVRQrL
          # K8s issue related: https://github.com/kubernetes/kubernetes/issues/81713
          #
          # args:
          #   - /bin/sh
          #   - -c
          #   - touch /tmp/healthy
          # livenessProbe:
          #   exec:
          #     command:
          #     - cat
          #     - /tmp/healthy
          #   initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          #   timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          #   successThreshold: {{ .Values.livenessProbe.successThreshold }}
          #   failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          # readinessProbe:
          #   exec:
          #     command:
          #     - cat
          #     - /tmp/healthy
          #   initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          #   timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          #   successThreshold: {{ .Values.readinessProbe.successThreshold }}
          #   failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        - name: {{ .Values.image.trap_subagent_name }}
          image: "{{ .Values.image.repository_trap_subagent }}:{{ .Values.image.tag_trap_subagent }}"
          imagePullPolicy: {{ .Values.image.pullPolicy_trap_subagent }}
          ports:
          - containerPort: 162
            protocol: TCP
          # Fail on liveness and readiness as here: https://bit.ly/3nVRQrL
          # K8s issue related: https://github.com/kubernetes/kubernetes/issues/81713
          #
          # livenessProbe:
          #   tcpSocket:
          #     port: 162
          #   initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          #   timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          #   successThreshold: {{ .Values.livenessProbe.successThreshold }}
          #   failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          # readinessProbe:
          #   tcpSocket:
          #     port: 162
          #   initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          #   timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          #   successThreshold: {{ .Values.readinessProbe.successThreshold }}
          #   failureThreshold: {{ .Values.readinessProbe.failureThreshold }}

      volumes:
      - name: snmpd-etc-volume
        configMap:
          name: {{ .Values.configmap.name_snmpd }}
      - name: snmpd-fm-volume
        configMap:
          name: {{ .Values.configmap.name_fm }}
