apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/name: {{ include "snmp.name" . }}
    helm.sh/chart: {{ include "snmp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: port-1
      port: 161
      protocol: UDP
      targetPort: 161
  selector:
    app.kubernetes.io/name: {{ include "snmp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
