#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: HelmRelease
metadata:
  name: snmp
  labels:
    chart_group: snmp
spec:
  releaseName: ns-snmp
  chart:
    spec:
      chart: snmp
      version: REPLACE_HELM_CHART_VERSION
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: snmp-static-overrides
      valuesKey: snmp-static-overrides.yaml
    - kind: Secret
      name: snmp-system-overrides
      valuesKey: snmp-system-overrides.yaml
